package com.example.pdfbox;

import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.text.PDFTextStripper;

import java.io.File;
import java.io.IOException;

/**
 * Apache PDFBox 基础演示
 *
 * 涵盖功能：
 * 1. 创建简单PDF文档（纯英文内容）
 * 2. 读取PDF文本内容
 * 3. 获取PDF元数据（页数、页面尺寸）
 * 4. 多页PDF创建与遍历
 */
public class PdfBoxBasicDemo {

    // 输出目录
    private static final String OUTPUT_DIR = "target/pdf-output/";

    public static void main(String[] args) throws IOException {
        // 创建输出目录
        new File(OUTPUT_DIR).mkdirs();

        System.out.println("===== Apache PDFBox Basic Demo =====\n");

        // 演示1：创建简单PDF
        demo1CreateSimplePdf();

        // 演示2：读取PDF文本
        demo2ReadPdfText();

        // 演示3：多页PDF创建与遍历
        demo3MultiPagePdf();

        System.out.println("\n===== Basic Demo Complete =====");
    }

    /**
     * 演示1：创建一个包含标题和段落的简单PDF
     * PDType1Font 是标准内嵌字体，无需额外字体文件，仅支持Latin字符
     */
    private static void demo1CreateSimplePdf() throws IOException {
        System.out.println("[Demo 1] Creating simple PDF...");
        String outputPath = OUTPUT_DIR + "basic_simple.pdf";

        // PDDocument 代表整个PDF文档，必须在finally或try-with-resources中关闭
        try (PDDocument document = new PDDocument()) {

            // 创建一个A4页面
            PDPage page = new PDPage(PDRectangle.A4);
            document.addPage(page);

            // 打开内容流，向页面写入内容
            try (PDPageContentStream contentStream =
                         new PDPageContentStream(document, page)) {

                // --- 写入标题 ---
                contentStream.beginText();
                // 设置字体和字号（PDType1Font.HELVETICA_BOLD 是标准粗体字体）
                contentStream.setFont(PDType1Font.HELVETICA_BOLD, 20);
                // 设置文字起始位置（坐标原点在页面左下角）
                // A4宽度约595pt，高度约842pt
                contentStream.newLineAtOffset(50, 750);
                contentStream.showText("Apache PDFBox Basic Demo");
                contentStream.endText();

                // --- 写入副标题 ---
                contentStream.beginText();
                contentStream.setFont(PDType1Font.HELVETICA_OBLIQUE, 12);
                contentStream.newLineAtOffset(50, 720);
                contentStream.showText("Generated by Apache PDFBox 2.0.31 - Java 8 Compatible");
                contentStream.endText();

                // --- 绘制分隔线 ---
                contentStream.setLineWidth(1.0f);
                contentStream.moveTo(50, 710);
                contentStream.lineTo(545, 710);
                contentStream.stroke();

                // --- 写入正文段落 ---
                contentStream.beginText();
                contentStream.setFont(PDType1Font.TIMES_ROMAN, 12);
                // setLeading 设置行间距（单位pt）
                contentStream.setLeading(18.0f);
                contentStream.newLineAtOffset(50, 690);

                // 逐行写入内容（换行用 newLine()）
                contentStream.showText("Apache PDFBox is an open source Java tool for working with PDF documents.");
                contentStream.newLine();
                contentStream.showText("It allows creation of new PDF documents, manipulation of existing documents,");
                contentStream.newLine();
                contentStream.showText("and the ability to extract content from documents.");
                contentStream.newLine();
                contentStream.newLine();
                contentStream.showText("Key Features:");
                contentStream.newLine();
                contentStream.showText("  - Create PDF documents from scratch");
                contentStream.newLine();
                contentStream.showText("  - Extract text and images from existing PDFs");
                contentStream.newLine();
                contentStream.showText("  - Merge and split PDF documents");
                contentStream.newLine();
                contentStream.showText("  - Add watermarks, annotations, and form fields");
                contentStream.newLine();
                contentStream.showText("  - Print PDF documents");
                contentStream.endText();

                // --- 绘制矩形边框装饰 ---
                contentStream.addRect(40, 580, 515, 130);
                contentStream.stroke();
            }

            // 保存文档
            document.save(outputPath);
            System.out.println("  Created: " + outputPath);

            // 输出文档基本信息
            System.out.println("  Pages: " + document.getNumberOfPages());
            PDPage savedPage = document.getPage(0);
            System.out.println("  Page size: " + savedPage.getMediaBox().getWidth()
                    + " x " + savedPage.getMediaBox().getHeight() + " pt (A4)");
        }
    }

    /**
     * 演示2：读取PDF文本内容
     * PDFTextStripper 是PDFBox最常用的文本提取工具
     */
    private static void demo2ReadPdfText() throws IOException {
        System.out.println("\n[Demo 2] Reading PDF text...");
        String inputPath = OUTPUT_DIR + "basic_simple.pdf";

        try (PDDocument document = PDDocument.load(new File(inputPath))) {

            // PDFTextStripper 按页面顺序提取文本
            PDFTextStripper stripper = new PDFTextStripper();

            // 可以指定提取的页范围（默认全部）
            stripper.setStartPage(1);
            stripper.setEndPage(document.getNumberOfPages());

            // 提取全部文本
            String fullText = stripper.getText(document);
            System.out.println("  Extracted text:");
            System.out.println("  ----------------------------------------");
            // 截取前300字符展示
            String preview = fullText.length() > 300
                    ? fullText.substring(0, 300) + "..."
                    : fullText;
            for (String line : preview.split("\n")) {
                System.out.println("  " + line);
            }
            System.out.println("  ----------------------------------------");
            System.out.println("  Total chars: " + fullText.length());

            // 按页提取
            System.out.println("\n  Page-by-page extraction:");
            for (int i = 1; i <= document.getNumberOfPages(); i++) {
                stripper.setStartPage(i);
                stripper.setEndPage(i);
                String pageText = stripper.getText(document);
                System.out.println("  Page " + i + ": " + pageText.trim().length() + " chars");
            }
        }
    }

    /**
     * 演示3：创建多页PDF并遍历页面
     * 展示如何在不同页面写入不同内容
     */
    private static void demo3MultiPagePdf() throws IOException {
        System.out.println("\n[Demo 3] Creating multi-page PDF...");
        String outputPath = OUTPUT_DIR + "basic_multipage.pdf";

        try (PDDocument document = new PDDocument()) {

            // 创建5个页面，每页显示页码和示例内容
            for (int pageNum = 1; pageNum <= 5; pageNum++) {
                PDPage page = new PDPage(PDRectangle.A4);
                document.addPage(page);

                try (PDPageContentStream cs = new PDPageContentStream(document, page)) {
                    // 页眉
                    cs.beginText();
                    cs.setFont(PDType1Font.HELVETICA_BOLD, 14);
                    cs.newLineAtOffset(50, 800);
                    cs.showText("Page " + pageNum + " of 5");
                    cs.endText();

                    // 页面主体内容
                    cs.beginText();
                    cs.setFont(PDType1Font.TIMES_ROMAN, 11);
                    cs.setLeading(16.0f);
                    cs.newLineAtOffset(50, 760);
                    cs.showText("This is page " + pageNum + " content.");
                    cs.newLine();
                    cs.showText("PDFBox makes it easy to create structured documents.");
                    cs.newLine();
                    cs.showText("Each page can have completely different layout and content.");
                    cs.endText();

                    // 页脚分隔线
                    cs.moveTo(50, 60);
                    cs.lineTo(545, 60);
                    cs.stroke();

                    // 页脚文字
                    cs.beginText();
                    cs.setFont(PDType1Font.HELVETICA, 9);
                    cs.newLineAtOffset(50, 45);
                    cs.showText("Apache PDFBox Multi-Page Demo | Page " + pageNum);
                    cs.endText();
                }
            }

            document.save(outputPath);
            System.out.println("  Created: " + outputPath + " (" + document.getNumberOfPages() + " pages)");

            // 遍历所有页面，获取尺寸信息
            System.out.println("  Page dimensions:");
            for (int i = 0; i < document.getNumberOfPages(); i++) {
                PDPage p = document.getPage(i);
                PDRectangle box = p.getMediaBox();
                System.out.printf("    Page %d: %.0f x %.0f pt (%.1f x %.1f mm)%n",
                        i + 1, box.getWidth(), box.getHeight(),
                        box.getWidth() * 25.4f / 72f, box.getHeight() * 25.4f / 72f);
            }
        }
    }
}
